apiVersion: apps/v1
kind: Deployment
metadata:
  name: adp-api
  namespace: { .Values.namespace }
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adp-api
  template:
    metadata:
      labels:
        app: adp-api
    spec:
      containers:
        - name: adp-api
          image: { .Values.adpApi.image.url }
---
apiVersion: v1
kind: Service
metadata:
  name: adp-api
  namespace: { .Values.namespace }
spec:
  selector:
    app: adp-api
  ports:
    - port: 80
      targetPort: 8080
