environment: adp-uat
namespace: adp-uat

adpApi:
  image:
    url: cloudbeesdemo/hackers-api:3.0-0.0.2
  hostname: adp-api.adp-uat.preview.cb-demos.io

adpWeb:
  image:
    url: your-registry/adp-web:latest
  hostname: adp-web.adp-uat.preview.cb-demos.io

adpAuth:
  image:
    url: cloudbeesdemo/hackers-auth:2.0-0.0.2
  hostname: adp-auth.adp-uat.preview.cb-demos.io
