environment: adp-prod
namespace: adp-prod

adpApi:
  image:
    url: cloudbeesdemo/hackers-api:3.0-0.0.2
  hostname: adp-api.adp-prod.preview.cb-demos.io

adpWeb:
  image:
    url: your-registry/adp-web:latest
  hostname: adp-web.adp-prod.preview.cb-demos.io

adpAuth:
  image:
    url: cloudbeesdemo/hackers-auth:2.0-0.0.2
  hostname: adp-auth.adp-prod.preview.cb-demos.io
